services:
  bird-prefix:
    build: .
    container_name: bird-prefix
    volumes:
      - ..:/bird-source
      - ./bird/test_prefix.conf:/bird-source/lab/bird/bird.conf:ro
    network_mode: bridge
    stdin_open: true
    tty: true
