log stderr all;

router id 192.0.2.99;

aspa table at;

filter valid_only {
  if aspa_check(at, bgp_path, true) = ASPA_VALID then accept;
  reject;
}

filter unknown_only {
  if aspa_check(at, bgp_path, true) = ASPA_UNKNOWN then accept;
  reject;
}

filter invalid_only {
  if aspa_check(at, bgp_path, true) = ASPA_INVALID then accept;
  reject;
}

protocol static aspa_data {
  aspa { table at; };

  route aspa 47065 {
    providers 600, 500;
    prefix 198.162.0.0/24 providers 200, 300, 400;
  };

  route aspa 300 {
    providers 100;
  };

  route aspa 500 {
    providers 100;
  };
}

protocol static valid_routes {
  ipv4 { import filter valid_only; };

  route 198.162.0.9/32 blackhole {
    bgp_path = prepend(bgp_path, 47065);
    bgp_path = prepend(bgp_path, 300);
    bgp_path = prepend(bgp_path, 100);
  };

  route 203.0.113.9/32 blackhole {
    bgp_path = prepend(bgp_path, 47065);
    bgp_path = prepend(bgp_path, 500);
    bgp_path = prepend(bgp_path, 100);
  };
}

protocol static unknown_routes {
  ipv4 { import filter unknown_only; };

  route 198.162.0.10/32 blackhole {
    bgp_path = prepend(bgp_path, 47065);
    bgp_path = prepend(bgp_path, 400);
    bgp_path = prepend(bgp_path, 100);
  };
}

protocol static invalid_routes {
  ipv4 { import filter invalid_only; };

  route 198.162.0.11/32 blackhole {
    bgp_path = prepend(bgp_path, 47065);
    bgp_path = prepend(bgp_path, 500);
    bgp_path = prepend(bgp_path, 100);
  };

  route 203.0.113.11/32 blackhole {
    bgp_path = prepend(bgp_path, 47065);
    bgp_path = prepend(bgp_path, 300);
    bgp_path = prepend(bgp_path, 100);
  };
}

protocol device {}
