log stderr all;

router id 192.0.2.99;

aspa table at;

protocol static aspa_data {
  aspa { table at; };

  route aspa 47065 providers 600, 500;
  route aspa 47065 prefix 198.162.0.0/24 providers 500, 800, 700;

  route aspa 300 providers 100;
  route aspa 500 providers 1000;
}

protocol device {}
