log "/dev/null" all;
router id 192.0.2.20;

aspa table at;

filter f {
    if aspa_check(at, bgp_path, true) = ASPA_INVALID then reject;
    accept;
}

protocol static aspa_data {
    aspa { table at; };

    route aspa 100 {
        providers 101, 65101, 65102;
        prefix 10.0.0.0/8 providers 101, 65201, 65202;
        prefix 11.0.1.0/24 providers 601, 702, 703;
    };
    route aspa 101 {
        providers 102, 66102, 66103;
    };
    route aspa 102 {
        providers 103, 66103, 66104;
    };
    route aspa 1100 {
        providers 1101, 66101, 66102;
        prefix 10.0.0.0/8 providers 1101, 66201, 66202;
        prefix 11.0.1.0/24 providers 1601, 1702, 1703;
    };
    route aspa 1101 {
        providers 1102, 67102, 67103;
    };
    route aspa 1102 {
        providers 1103, 67103, 67104;
    };
}

protocol static test_routes {
    ipv4 { import filter f; };

    route 10.0.0.0/32 blackhole {
        bgp_path = prepend(bgp_path, 100);
        bgp_path = prepend(bgp_path, 101);
        bgp_path = prepend(bgp_path, 102);
        bgp_path = prepend(bgp_path, 103);
    };
    route 10.0.0.1/32 blackhole {
        bgp_path = prepend(bgp_path, 1100);
        bgp_path = prepend(bgp_path, 1101);
        bgp_path = prepend(bgp_path, 1102);
        bgp_path = prepend(bgp_path, 1103);
    };
    route 10.0.0.2/32 blackhole {
        bgp_path = prepend(bgp_path, 100);
        bgp_path = prepend(bgp_path, 101);
        bgp_path = prepend(bgp_path, 102);
        bgp_path = prepend(bgp_path, 103);
    };
    route 10.0.0.3/32 blackhole {
        bgp_path = prepend(bgp_path, 1100);
        bgp_path = prepend(bgp_path, 1101);
        bgp_path = prepend(bgp_path, 1102);
        bgp_path = prepend(bgp_path, 1103);
    };
}

protocol device {}
